### ISSUE TITLE
Deleted copy constructor and copy assingnment operator incorrectly checked by script

### ISSUE THREAD

**Issue by Aleksiiej** [coders-school/memory-management#175]
![Screenshot from 2022-07-05 22-31-22](https://user-images.githubusercontent.com/94867075/177412284-45acb03f-92fd-4d12-9556-34e3375f91e2.png)
![Screenshot from 2022-07-05 22-32-34](https://user-images.githubusercontent.com/94867075/177412287-745d87bf-0161-4088-84e7-811078fd9b71.png)

Deleted copy constructor and copy assingnment operator incorrectly detected as not implemented.

**Comment by ziobron** [comment]
🏅 2 XP granted for @Aleksiiej
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Thanks! I have just fixed this issue. It's always a good practice to have `const &` in copy constructors to make sure that you can't modify the source object, but yes, even without this const it is still a copy constructor. 
Please rebase your PR.
