### ISSUE TITLE
Outdated file-existence-action version

### ISSUE THREAD

**Issue by michalsoloducha** [coders-school/memory-management#193]
Since October 2022 there is a new version of the file-existence-action. In `.github/workflows/main.yml` the line
```uses: andstor/file-existence-action@v1``` should be changed to ```uses: andstor/file-existence-action@v2```

Check official repository for reference:
https://github.com/andstor/file-existence-action

**Comment by ziobron** [comment]
🏅 2 XP granted for @michalsoloducha
Thanks for raising this Issue to help to make the course better!
