### ISSUE TITLE
Outdated links found in README 

### ISSUE THREAD

**Issue by DarioDarioCS** [coders-school/memory-management#197]
In homework's readme:

https://github.com/coders-school/memory-management/tree/shared_ptr/homework/shared_ptr

I found outdated links:
"Pre-work
Read the [presentation about move semantics and std::forward](https://github.com/coders-school/modern-cpp/raw/master/module3/move_semantics.pdf)
Read the [variadic template part of this presentation](https://github.com/coders-school/kurs_cpp_lato_2019/raw/master/L07-modern-cpp/modern_cpp.pdf)
It will be useful for a post-work ;)"

**Comment by ziobron** [comment]
🏅 2 XP granted for @DarioDarioCS
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Move semantics link fixed :)
