### ISSUE TITLE
 permission error

### ISSUE THREAD

**Issue by gyrydymptum** [coders-school/memory-management#63]
Wskaźniki inteligentne
0x0C ResourceFactory
https://user-images.githubusercontent.com/77102726/134931566-f4ec50eb-5c0c-4181-a307-7ad1b77f1d65.png

**Comment by ziobron** [comment]
🏅 2 XP granted for @gyrydymptum
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Should be fixed now. Thanks!
