### ISSUE TITLE
A testcase could be more general

### ISSUE THREAD

**Issue by michalsoloducha** [coders-school/memory-management#99]
On brunch `resource` in `memory-management/.github/scripts/check.sh` one testcase assumes that user didn't modify the file before pushing to the server:
`pattern ${FILE} "Looking for the allocation place" "main \(resourceD.cpp:30\)"`

**Comment by ziobron** [comment]
🏅 2 XP granted for @michalsoloducha
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Thanks, fixed by merging #100
